//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapyApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kapymvc1Entities : DbContext
    {
        public kapymvc1Entities()
            : base("name=kapymvc1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<ActionRecord> ActionRecords { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<News1> News1 { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Source> User_Source { get; set; }
    }
}
